---
- name: Setup Backend Node.js Server
  hosts: backend
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install nvm
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      args:
        creates: "/home/{{ ansible_user }}/.nvm/nvm.sh"

    - name: Install Node.js 18
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 18
      args:
        executable: /bin/bash
        creates: "/home/{{ ansible_user }}/.nvm/versions/node/v18.*/bin/node"

    - name: Ensure repository directory is owned by the correct user
      file:
        path: "/home/{{ ansible_user }}/r-queue"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: directory

    - name: Clone project repository
      git:
        repo: "{{ project_repo }}"
        dest: "/home/{{ ansible_user }}/r-queue"
        version: main

    - name: Install pm2 globally
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm install -g pm2
      args:
        executable: /bin/bash

    - name: Install npm dependencies
      shell: |
        cd /home/{{ ansible_user }}/r-queue/server
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm install
      args:
        executable: /bin/bash

    - name: Update .env file with Redis configuration
      lineinfile:
        path: "/home/{{ ansible_user }}/r-queue/server/.env"
        line: "{{ item }}"
        create: yes
      with_items:
        - "REDIS_HOST={{ redis1_private_ip }}"
        - "PORT=5000"
      notify:
        - Restart backend server with pm2

    - name: Start backend server with pm2
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        cd /home/{{ ansible_user }}/r-queue/server
        pm2 start npm --name "backend" -- run dev
      args:
        executable: /bin/bash

  handlers:
    - name: Restart backend server with pm2
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        cd /home/{{ ansible_user }}/r-queue/server
        pm2 restart backend
      args:
        executable: /bin/bash