- name: Setup Backend Node.js Server
  hosts: backend
  become: true
  vars_files:
    - ../vars.yml
  
  tasks:
    - name: Update apt cache and install nodejs & npm
      apt:
        name: ['nodejs', 'npm']
        update_cache: yes
        state: present
      become: true

    - name: Clone project repository
      git:
        repo: "{{ project_repo }}"
        dest: "/home/{{ ansible_user }}/r-queue"
        force: yes

    - name: Install project dependencies
      shell: |
        cd /home/{{ ansible_user }}/r-queue/server
        npm install
      args:
        executable: /bin/bash

    - name: Create .env file
      copy:
        dest: "/home/{{ ansible_user }}/r-queue/server/.env"
        content: |
          REDIS_HOST={{ redis1_private_ip }}
          PORT={{ backend_port }}
        mode: '0644'

    - name: Start server with nodemon
      shell: |
        cd /home/{{ ansible_user }}/r-queue/server
        npm run dev
      args:
        executable: /bin/bash
        async: 1000
        poll: 0

    - name: Show backend URL
      debug:
        msg: "Backend is available at: http://{{ nodejs_public_ip }}:{{ backend_port }}"