- name: Setup Frontend for React project
  hosts: frontend
  become: true
  vars:
    app_dir: /home/ubuntu/r-queue
    nginx_conf_path: /etc/nginx/sites-available/react-app
    backend_url: "http://{{ nodejs_public_ip }}:5000"

  tasks:
    - name: Update system and install necessary packages
      apt:
        update_cache: yes
        upgrade: yes
        name:
          - curl
          - git
          - nginx
        state: present

    - name: Install nvm
      shell: |
        sudo -u ubuntu bash -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash"
        export NVM_DIR="/home/ubuntu/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
      args:
        creates: "/home/ubuntu/.nvm/nvm.sh"
        executable: /bin/bash

    - name: Install Node.js 18 using nvm
      shell: |
        export NVM_DIR="/home/ubuntu/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 18
      args:
        executable: /bin/bash
      become_user: ubuntu

    - name: Ensure repository directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Clone the r-queue project repository
      git:
        repo: "https://github.com/BayajidAlam/r-queue.git"
        dest: "{{ app_dir }}"
        version: main
        force: yes
      become_user: ubuntu

    - name: Install project dependencies for the frontend
      shell: |
        export NVM_DIR="/home/ubuntu/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        cd {{ app_dir }}/client
        npm install
      become_user: ubuntu

    - name: Build React application
      shell: |
        export NVM_DIR="/home/ubuntu/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        cd {{ app_dir }}/client
        npm run build
      become_user: ubuntu

    - name: Create Nginx configuration
      template:
        src: nginx.conf.j2
        dest: "{{ nginx_conf_path }}"
      notify: Reload Nginx

    - name: Enable Nginx site configuration
      file:
        src: "{{ nginx_conf_path }}"
        dest: /etc/nginx/sites-enabled/react-app
        state: link
      notify: Reload Nginx

    - name: Ensure .env file exists in the client directory
      copy:
        content: "VITE_PUBLIC_API_URL={{ backend_url }}"
        dest: "{{ app_dir }}/client/.env"
        owner: ubuntu
        group: ubuntu

    - name: Print frontend access details
      debug:
        msg: "Frontend is accessible at http://{{ ansible_host }}"

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded