version: "3.8"
services:
  redis1:
    image: redis:latest
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --bind 0.0.0.0
    ports:
      - "6379:6379"
      - "16379:16379"
    networks:
      - redis-net

  redis2:
    image: redis:latest
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --bind 0.0.0.0
    ports:
      - "6380:6379"
      - "16380:16379"
    networks:
      - redis-net

  redis3:
    image: redis:latest
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --bind 0.0.0.0
    ports:
      - "6381:6379"
      - "16381:16379"
    networks:
      - redis-net

  redis4:
    image: redis:latest
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --bind 0.0.0.0
    ports:
      - "6382:6379"
      - "16382:16379"
    networks:
      - redis-net

  redis5:
    image: redis:latest
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --bind 0.0.0.0
    ports:
      - "6383:6379"
      - "16383:16379"
    networks:
      - redis-net

  redis6:
    image: redis:latest
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --bind 0.0.0.0
    ports:
      - "6384:6379"
      - "16384:16379"
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge