version: "3"

services:
  redis-node-1:
    image: redis:7
    container_name: redis-node-1
    ports:
      - "6379:6379"
    volumes:
      - ./redis-cluster/node-1/data:/data
      - ./redis-cluster/node-1/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster-network

  redis-node-2:
    image: redis:7
    container_name: redis-node-2
    ports:
      - "6380:6379"
    volumes:
      - ./redis-cluster/node-2/data:/data
      - ./redis-cluster/node-2/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster-network

  redis-node-3:
    image: redis:7
    container_name: redis-node-3
    ports:
      - "6381:6379"
    volumes:
      - ./redis-cluster/node-3/data:/data
      - ./redis-cluster/node-3/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster-network

  redis-node-4:
    image: redis:7
    container_name: redis-node-4
    ports:
      - "6382:6379"
    volumes:
      - ./redis-cluster/node-4/data:/data
      - ./redis-cluster/node-4/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster-network

  redis-node-5:
    image: redis:7
    container_name: redis-node-5
    ports:
      - "6383:6379"
    volumes:
      - ./redis-cluster/node-5/data:/data
      - ./redis-cluster/node-5/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster-network

  redis-node-6:
    image: redis:7
    container_name: redis-node-6
    ports:
      - "6384:6379"
    volumes:
      - ./redis-cluster/node-6/data:/data
      - ./redis-cluster/node-6/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster-network

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    networks:
      - redis-cluster-network

networks:
  redis-cluster-network:
    driver: bridge
