---
frontend_public_ip: "54.179.63.41"
nodejs_public_ip: "18.143.100.36"
redis1_private_ip: "10.0.2.173"
redis2_private_ip: "10.0.2.197"
redis3_private_ip: "10.0.2.50"
redis4_private_ip: "10.0.3.72"
redis5_private_ip: "10.0.3.63"
redis6_private_ip: "10.0.3.83"
backend_port: 5000
